version: "3.3"
services:
  nginx:
    image: nginx:1.15.4-alpine
    volumes:
      - ../todo-app/build:/app
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
  mysql:
    image: 
    env:
      - ROOT_PASSWORD=